-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 14:56:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_gen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gen` DEFAULT CHARACTER SET utf8 ;
USE `db_gen` ;

-- -----------------------------------------------------
-- Table `db_gen`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gen`.`tb_usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gen`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gen`.`tb_categoria` (
  `id_categoria` INT NOT NULL,
  `tipo_residuo` VARCHAR(255) NULL,
  `cadastro_residuo` VARCHAR(255) NULL,
  `tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gen`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gen`.`tb_produto` (
  `id_produto` INT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NULL,
  `data_retirada` DATETIME NULL,
  `imagem` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `tb_usuario_id_usuario` INT NOT NULL,
  `tb_categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `tb_usuario_id_usuario`, `tb_categoria_id_categoria`),
  INDEX `fk_tb_produto_tb_usuario_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria1_idx` (`tb_categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_usuario`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `db_gen`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`tb_categoria_id_categoria`)
    REFERENCES `db_gen`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;